### ISSUE TITLE
Unable to install and can't locate installation instructions

### ISSUE THREAD

**Issue by sol2014** [AppertaFoundation/SuiteCRM-NHS-Edition#1]
#### Issue
I am unable to successfully install/test this version (SuitecrmNHS)

#### Possible Fix
Please point me to the installation file.

#### Your Environment

* SuiteCRM Version used:
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):
* Environment name and version (e.g. MySQL, PHP 7):
* Operating System and version (e.g Ubuntu 16.04):

**Comment by willrennie** [comment]
Have you set up a web server to install SuiteCRM on? I'd recommend you read the installation guide on our wiki: https://suitecrm.com/wiki/index.php/Installation

**Comment by sol2014** [comment]
I installed it but this version is not good. It's quite clunky and incomplete looking on my end.

**Comment by sol2014** [comment]
I like Suitecrm but I'm confused as to what makes the NHS different. There's no information on it and other than the icons looking different, a very clunky and unprofessioal look and I also don't see any new modules, extensions, etc that would indicate how this differs from the other versions. This reminds me of a project a client partially paid for and received partial work.

**Comment by mattglover11** [comment]
Any progress on this?

**Comment by sol2014** [comment]
Matt,

I managed to install it but I was quite disappointed. This is an incomplete or not even near completed project. Other than some image changes, I don't see any difference in this version other than it looks and operates terribly and most importantly, there's no visible/perceived changes that makes this system better for the Healthcare industry. There's absolutely nothing that makes it healthcare related so I am completely confused as to its purpose/point. The Aperta website speak of their clinicians but unless all the changes have been made in a way to make it more HIPPA compliant, I don't see any value. As a matter of fact, this version's aesthetics fall quite short. I'm hoping this was a start to get and gaze interest and that they'd bring in council in the medical fields to help make it more suitable for the industry.

**Comment by mattglover11** [comment]
Hey Sol,

Thanks - we are just making the same assessment. I'm forming the opinion that this project is either in its infancy or that they have only just started making the source tree visible, or that there is a database script missing that applies their configuration of the modules that is not self-evident or not uploaded.

We're based in Melb, Australia - looking to reach out to Apperta/SuiteCRM by phone now to get to the bottom of it.

**Comment by sol2014** [comment]
Matt,

Absolutely, I was boasting to a client that owns a private duty nursing company because I know the SuiteCRM team push out some incredible software but this one left me confused and disappointed. They've not replied to my comment on it on LinkedIn either so I wasn't sure about where to go from there.

It does sound amazing but only if they can truly deliver on the promises. Please keep me posted.

Thanks!

**Comment by SVRoberts** [comment]
Hi Sol,
I work with Matt. I've just sent a message to Richard Jefferson who seems to be the NHS representative on the Aperta board for this project. There is no phone number for NHS as it seems to be a 'Community Interest' group. I've sent an InMail to Richard via LinkedIn and hope to receive a reply and keep us all updated.
Steve

**Comment by mattglover11** [comment]
@willrennie Do you work for Aperta/SuiteCRM? Can you shed any light on this while we wait on a response from Richard?

**Comment by sol2014** [comment]
If they need some assistance/input in this, I'd be more than glad to. I've used SuiteCRM and a few other open source ERP and CRMs and I have good connections with hospitals, medical practices and in-home nursing care facilities due to my special needs son and can provide valuable input or locate small fundings in order to get his going but I am trying to see what they have first before fully committing. I believe there's an excellent future for this version if done properly. 

Ending the night now, talk to you all later today.

**Comment by willrennie** [comment]
This is a fork created from the parent SuiteCRM repository to allow the Apperta NHS team to develop upon/add to the core SuiteCRM application and have this as a separate repository for people to work on and contribute to. Any questions regarding this should be directed to the Apperta/NHS teams as they will be able to inform you about how this project will progress and be maintained going forward.

**Comment by mattglover11** [comment]
Hi @willrennie thank you for the update - I interpret that to mean that we've misunderstood the press releases. Based on one particular article, it appeared to suggest that you had already deployed an NHS centric adaptation of SuiteCRM and that this was the repo that contained the stack that NHS are already using. I think I am right then in saying that project is only just beginning and that there us currently no customer care centric version of SuiteCRM yet in existence for NHS.

**Comment by willrennie** [comment]
As previously stated, please contact the relevant teams if you have any issues or questions about this project.

**Comment by david-jobling** [comment]
Hi @sol2014 / @mattyglover / @SVRoberts , 

Thank you for your feedback and comments. As per Will's comment, the health and care community aim to develop upon/add to the core SuiteCRM application.  I support Apperta and would be happy to answer any questions you may have and discuss how you could get involved with the community? Please email at d.jobling@nhs.net

**Comment by mattglover11** [comment]
HI David,

Thanks for the note! I think the thing that got us excited was the press release which reads "The SuiteCRM NHS edition has all features, functionality and modules readily available when downloaded ensuring everyone can utilise every feature and functionality straight away. This enterprise ready CRM solution can deployed in a local or cloud based platform and has no user restrictions." 

I think our general confusion is that the statement appears to be aspirational rather than a fact. As a project team that could really have leveraged this, we spent a good day (* 3 resources) trying to get the SuiteCRM NHS edition to work as the press release claims the NHS features are "readily available".

What it should say is that at the completion of the project, the NHS features will be made available - I'm guessing late 2017?

**Comment by mattglover11** [comment]
Nevertheless @SVRoberts will be in touch as we are inclined to have our client align with your project if the timelines and functional roadmaps converge well enough.

**Comment by david-jobling** [comment]
Hi Matt, 

I can understand the confusion. The current edition should have all of the features you would expect with SuiteCRM; further NHS functionality will be designed and developed by the health and care community over time and released with the SuiteCRM NHS Edition as they are available. 

I would welcome a discussion on it; I would be happy to chat via Skype?

**Comment by SVRoberts** [comment]
@david-jobling,
I would love to chat with you further on this. My Skype is: svroberts
Are you available for a brief chat today?
Steve

**Comment by gregsoper** [comment]
There are a number of things that need to be appreciated:

1. SuiteCRM needs technical skills to install properly and good knowledge of the application to configure. If it is "quite clunky and incomplete looking on my end" there is a strong likelihood that one or both of the foregoing conditions have not been met.

2. If you read back through the press release, it does not mention or promise ANY NHS specific functionality. It states "The SuiteCRM NHS edition has all features, functionality and modules readily available" .. which is true. It is an enterprise-grade generic CRM made available to the Apperta foundation to innovate on with the support of the SuiteCRM project.

3. Finally. A little respect would go a long way. Some of the language in this thread has been rather emotive. We at the SuiteCRM project have given of our time in order to provide this software to the Apperta Foundation at no charge. SuiteCRM is used by large corporate organisations for deep strategic purposes. It is a great application. About that I will brook no argument. Some professional input into how the health sector can take what is there and build on it would be more appreciated.

**Comment by sol2014** [comment]
@gregsoper wow! That 3rd statement was strange to say the least. No one's being disrespectful. The article was slightly misleading and I was providing a review of my findings. I am not as articulate as the other gentlemen providing their input/review so please don't see this as an attack on SuiteCRM or this project. I am typically very direct but am never intentionally trying to upset/disrespect a fellow human being. I'm well versed with SuiteCRM/SugarCRM CE. I've used and worked with various versions of the two since 2011 as well as other open source products. I believe the article is missing key information that has led me and apparently a few others to think that Apperta has made their own customizations/modifications to the system that would more align it with the healthcare industry. Again, I am direct and not as articulate as the other gentlemen. I was just excited to checkout what NEW things the NHS version had to offer. 

I installed it and it wasn't as visually appealing as the current versions of SuiteCRM. That is my personal experience that I've shared and I think if you install the NHS version you will see what I was attempting to articulate. 

In all business whether the software is open source, free or for pay, there's always going to be all types of reviews and the your third statement has made me feel that all reviews must be positive or someone will think we are being disrespectful. Not good.

**Comment by gregsoper** [comment]
"I installed it and it wasn't as visually appealing as the current versions of SuiteCRM"

It is the same as the current versions of SuiteCRM. Hence Point #1 in my first post. If you don't install it properly it won't perform or look as it should. 

I stand by my Point # 3. If you don't know how to install it properly, then please do not blame the software. Statements like "This is an incomplete or not even near completed project." will not win you many plaudits with people who know, love, respect and understand SuiteCRM.

**Comment by sol2014** [comment]
Whoa... who's trying to win anything here? If I incorrectly installed it then yes that's on me but you seem to have a fundamental issue with any criticism that isn't not positive towards the system. I wasn't trying to win ANYTHING let alone "plaudits." My statements still remain true and they still stand. 

Nobody's trying to bash SuiteCRM in anyway here so not sure why you are trying to make such an argument. I've done nothing but complimented SuiteCRM and it's abilities. I've been only discussing my experience with this NHS version and I still say the article was missing information that led me and apparently a few others to think that it had components/modules/extensions or some coding that pertained to the healthcare industry. 

Regardless whether it operates just like the current SuiteCRM - which I doubt because the icons and template on my installation looked totally different then what it looks like on the current SuiteCRM - that article led me and a few others to think there was more to this version that would pertain to the healthcare industry. I was unaware until today that this is the beginning stages of this project and that someone could have simply downloaded the currently version of SuiteCRM instead of the NHS. I will share screen shots of just how different it looks once installed shortly.

**Comment by sol2014** [comment]
This is the beginning stages of installation where after it's done the checks and gives the green light so this is numbered 1. I have 6 images that will shed some light on what I have been trying to explain but again, my articulation is not as well written as most here but that doesn't mean that I am being negative nor disrespectful to anyone or the works that have been done on SuiteCRM. Just misunderstood that NHS has nothing relating to the healthcare industry for the moment. 

Here are the screenshots below:

1. https://ibin.co/35H7uBwXEUIB.jpg
2. https://ibin.co/35H9hxw1Qw3U.jpg
3. https://ibin.co/35HA1K6KAoEa.jpg
4. https://ibin.co/35HA7sboWTnj.jpg
5. https://ibin.co/35HAFgXy4xAd.jpg
6. https://ibin.co/35HDWJZoEMq1.jpg - Admin section

I don't think I'm crazy but if I am then I am more then willing to understand where I went wrong on this installation.

**Comment by willrennie** [comment]
I've just cloned and installed and don't experience any of these issues. From what I can see this looks like permissions. Are you downloading the zip and installing or using git to clone and install? What environment(OS, PHP version etc.) are you installing on?

**Comment by sol2014** [comment]
@willrennie I typically use a GoDaddy account to test SuiteCRM. I have PHP 5.5.38 - Linux
I downloaded the zip file, uploaded it to the GoDaddy account, unzipped it while in the File Manager. Verified file permissions based on the installation page of SuiteCRM and proceeded to install. All checks came fine prior to installation per first image. I just redownloaded the file and am about to install it on another account. I will update you on what happens.

Also, I created the db prior to install. I also installed the demo files per image 2. I will attempt install without demo data shortly as well.

**Comment by mattglover11** [comment]
@sol2014 @willrennie Just a heads up @SVRoberts and our system admin (Tim) have managed to get the stylesheet stuff sorted out with some permission or other updates and we have a good looking app again! 

@SVRoberts could you please ask Tim to update this issue with the steps taken?

**Comment by sol2014** [comment]
@mattyglover My apologies for the long wait to reply but I felt I had to pull back from this as it seemed like what I was trying to point out was being perceived as an aggression or me being disrespectful with regards to the SuiteCRM project, it's members and all who enjoy it. This was never the case and unfortunately, I was unsuccessful at expressing it. What's depressing is I've been pitching SuiteCRM to just about any business connection I meet/met because I've completed basic implementations (no code modification) for a small company.

I came back to check this out and confirm whether or not I was doing something wrong or if I were going crazy, etc. Could you please let me know if I was doing something wrong within the permissions? Was this an error located by you @mattyglover?

**Comment by SVRoberts** [comment]
@sol2014 Sorry for the long delay. We have solved the problem with this install and it has to do with the permissions (We didn't have these issues with the vanilla package btw) . Tomorrow I will hear from our Sys Admin with regards to exactly which permissions made this work. The package looks the same as the vanilla install.
I have also had an extensive chat with NHS as to the status of this project. As a CRM platform, it is fully functional and is currently being used. As a 'patient management system' (insert correct term here) this project has not yet started. As far as I know, there is little if any difference between Suite CRM and Suite CRM NHS edition. This is where all the confusion is coming from. I guess we all assumed that NHS would require a patient management system and that this functionality would be included in it's badged version. This is not necessarily the case. I'm guessing the team at Sales Agility will be developing this at some stage? Is there a request for this in place?
@gregsoper Do you have anything to add on any 'patient management' functionality for the NHS edition and if there are plans to add this in the future?

**Comment by SVRoberts** [comment]
@sol2014 Here is what we did to make the NHS edition look just like the vanilla edition.
You need to run the following (replacing angle brackets appropriately): 
chown -R <username>:<groupname> <SuiteCRM directory>
The exact values of username, groupname, and SuiteCRM directory vary from system to system.
Not sure where we go from here. If someone was willing to support us financially in some way we would be keen to develop the patient management modules for Suite CRM NHS Ed.

**Comment by SVRoberts** [comment]
@sol2014 Did you see the post I made on Github? Not sure if you are notified after the discussion is closed.

Tim, our SysAdmin said “You need to run the following (replacing angle brackets appropriately): chown -R <username>:<groupname> <SuiteCRM directory>
The exact vaules of username, groupname, and SuiteCRM directory vary from system to system.

I hope this helps

Steve

**Comment by gregsoper** [comment]
@SVRoberts 

"As far as I know, there is little if any difference between Suite CRM and Suite CRM NHS edition."

Correct

" I guess we all assumed that NHS would require a patient management system and that this functionality would be included in it's badged version."

The NHS would benefit from an open source patient management system. But there is a lot of work to do before one is available:

1. There needs to be sponsor(s)
2. There needs to be budget
3. There needs to be a comprehensive scoping exercise
4. There needs to be a community of collaborators
5. There needs to be a community leader

None of those are currently in place.

"Do you have anything to add on any 'patient management' functionality for the NHS edition and if there are plans to add this in the future?"

See above.

THE NHS Edition is just a small part of what we do. It's not our focus. It's the seed which, if germinated, will deliver a more open, less costly, more agile patient management system. But it needs the NHS to engage and to put some drive behind this. We're are willing participants but we are not NHS experts.

**Comment by sol2014** [comment]
@SVRoberts I've been getting some demos of hospital, hospice and homecare software systems in order to gauge what they have that the open source  systems don't so I didn't get a chance to revisit the NHS edition and since there weren't any changes, I didn't see a reason. I terribly misunderstood the version in the beginning which I believe led to something I try to avoid when on blogs/forums, etc. 

But, after doing some demos of paid systems. I've found some valuable information. First thing if it's going to be a medical application is that it must comply with EU GDPR and/or HIPPA. Second thing is point of entry. I believe the first steps is to select a specific market that doesn't have a lot of competitors (open source software wise) and that has a ton of potential clients. As I mentioned before, I have special needs son so that places me within a bias for homecare but it's a huge market and even the smaller operations can generate millions with just 10 homecare clients depending on country, state, medical coverage types and needs. They are paying between $300 per month for basic systems and can go past the tens of thousands. 

Most of the things I've seen, can be easily done on a module/extension level and be sold on a SaaS basis but there are a set of basics that the base system must have. I plan on configuring SuiteCRM in a way that will mimic one of the systems that I demo'd as much as possible without any coding and see how far can I get. I don't know how to code but I understand business process layout and once I understand how a software operates, I can figure out how to setup a system with minimal code level changes. I believe there's a seriously untapped market out there for this and tremendous opportunity for those with vision, that can see the future benefits but some basic outlining of needs would have to be created. 

Don't know much about the processes involved in coding in order to write out a scoping exercise but I can write out the processes that are involved when using the system and how to make SuiteCRM do as much of it out of the box. I will post my findings once completed.

**Comment by sol2014** [comment]
By the way, here's a list of some capabilities that most decent systems for these industries possess.

Billing & Invoicing for various sources such as Medicare/Medicaid, etc, Charting, Electronic Signature, Employee Tracking, Medication Database, Time/Task Reporting, DDE, EDI, OASIS, Point of Care, Payroll, Medicare Eligibility Verification, 485, Billing, Scheduling, Physician Portal, Patient Portal, Employee Portal, Progress Notes, Outlier Management Tools, Intake Management, Admissions, Functionalities relating to specific homecare companies such as those who focus on Pediatrics, Hospice, Private Duty, etc. Most of the modules out there can be re-purposed/renamed and modified in order to fulfill these requirements and the majority of the items listed are forms and/or processes that can be customized. The biggest hurdle is going to be the compliance factor which anyone can make a module or extension that ensures this is done correctly and continuously track and monitor the system.
